name: Docs
on:
  pull_request:
    branches: [docs]
  push:
    branches: [docs]

jobs:
  build_publish:
    name: Generate Docs
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Coursier Cache
        uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Build docs
        run: ./build-docs.sh
      - name: Publish docs
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.BUILD_BOT_SSH_PRIVATE_KEY }}
          publish_dir: ./target
          publish_branch: gh-pages
